name: "Praying With the Church - A Catholic Podcast"
description: "Prayer in the Catholic Tradition"
author: Joshua Michael
email: josh@nowealthbutlife.com
pygments: false
base_url: "http://pwcpodcast.com"